package persistencias;
// Generated 14 feb 2024 12:59:15 by Hibernate Tools 5.4.33.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cantantes generated by hbm2java
 */
@Entity
@Table(name="cantantes", catalog="censo_europa")
public class Cantantes implements java.io.Serializable {

	private String pais;
	private String nombre;
	private String nombreCancion;

	public Cantantes() {
	}

	public Cantantes(String pais, String nombre) {
		this.pais = pais;
		this.nombre = nombre;
	}

	public Cantantes(String pais, String nombre, String nombreCancion) {
		this.pais = pais;
		this.nombre = nombre;
		this.nombreCancion = nombreCancion;
	}
	@Id
	@Column(name="PAIS")
	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}
	
	@Column(name="NOMBRE")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	
	@Column(name="NOMBRE_CANCION")
	public String getNombreCancion() {
		return this.nombreCancion;
	}

	public void setNombreCancion(String nombreCancion) {
		this.nombreCancion = nombreCancion;
	}

}
