package persistencias;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated 14 feb 2024 12:59:15 by Hibernate Tools 5.4.33.Final

/**
 * PaisesVotos generated by hbm2java
 */
@Entity
@Table(name="paises_votos", catalog="censo_europa")
public class PaisesVotos implements java.io.Serializable {

	private String pais;
	private String primerPuesto;
	private String segundoPuesto;
	private String terceroPuesto;

	public PaisesVotos() {
	}

	public PaisesVotos(String pais, String primerPuesto, String segundoPuesto, String terceroPuesto) {
		this.pais = pais;
		this.primerPuesto = primerPuesto;
		this.segundoPuesto = segundoPuesto;
		this.terceroPuesto = terceroPuesto;
	}
	
	@Id
	@Column(name="PAIS")
	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	@Column(name="PRIMER_PUESTO")
	public String getPrimerPuesto() {
		return this.primerPuesto;
	}

	public void setPrimerPuesto(String primerPuesto) {
		this.primerPuesto = primerPuesto;
	}

	@Column(name="SEGUNDO_PUESTO")
	public String getSegundoPuesto() {
		return this.segundoPuesto;
	}

	public void setSegundoPuesto(String segundoPuesto) {
		this.segundoPuesto = segundoPuesto;
	}

	@Column(name="TERCERO_PUESTO")
	public String getTerceroPuesto() {
		return this.terceroPuesto;
	}

	public void setTerceroPuesto(String terceroPuesto) {
		this.terceroPuesto = terceroPuesto;
	}

}
