package persistencia;
// Generated 7 feb 2024 13:02:00 by Hibernate Tools 5.4.33.Final

/**
 * PaisesVotos generated by hbm2java
 */
public class PaisesVotos implements java.io.Serializable {

	private String pais;
	private String primerPuesto;
	private String segundoPuesto;
	private String terceroPuesto;

	public PaisesVotos() {
	}

	public PaisesVotos(String pais, String primerPuesto, String segundoPuesto, String terceroPuesto) {
		this.pais = pais;
		this.primerPuesto = primerPuesto;
		this.segundoPuesto = segundoPuesto;
		this.terceroPuesto = terceroPuesto;
	}

	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	public String getPrimerPuesto() {
		return this.primerPuesto;
	}

	public void setPrimerPuesto(String primerPuesto) {
		this.primerPuesto = primerPuesto;
	}

	public String getSegundoPuesto() {
		return this.segundoPuesto;
	}

	public void setSegundoPuesto(String segundoPuesto) {
		this.segundoPuesto = segundoPuesto;
	}

	public String getTerceroPuesto() {
		return this.terceroPuesto;
	}

	public void setTerceroPuesto(String terceroPuesto) {
		this.terceroPuesto = terceroPuesto;
	}

}
